### ISSUE TITLE
Desktop build doesn't connect to ColoredCoins API on testnet

### ISSUE THREAD

**Issue by msmarcal** [Colored-Coins/colored-coins-copay-wallet#5]
An error occurs when clicking on "view assets" in a testnet wallet:

<img width="912" alt="Testnet wallet" src="https://user-images.githubusercontent.com/11068537/29186544-72ee2018-7dd2-11e7-8eca-aaa66fed9a69.png">
 
Is this supposed to work or it wasn't implemented?

**Comment by troggy** [comment]
thanks for the report. It is clearly an issue — the app should work for both testnet and mainnet

**Comment by troggy** [comment]
@msmarcal Marcelo, the issue should be resolved now. Please rebuild from the latest source and try again.

**Comment by troggy** [comment]
> Is this supposed to work or it wasn't implemented?

I can say that the answer is "it wasn't implemented". The code always assumed that the wallet has ColoredCoins RPC server running along on the same host and port. Obviously, this assumption failed for mobile/desktop/chrome builds and most of the web setups.

Now it explicitly uses https://copay.coloredcoins.org/api/ as a ColoredCoins RPC endpoint. This should work for all the platforms and network. It is hardcoded for now, so if you want to use your own ColoredCoins node, you need to change the URLs in the code. Later I will probably make this configurable. The project needs more love :(
